# Phishing link classifier

For the phishing URL-data I will be using https://archive.ics.uci.edu/dataset/967/phiusiil+phishing+url+dataset -dataset, that includes 134,850 legitimate and 100,945 phishing URLs

In [ ]:
import pandas as pd
from ucimlrepo import fetch_ucirepo 

phiusiil_phishing_url_website = fetch_ucirepo(id=967)

The dataset includes URL:s and their features in `phiusiil_phishing_url_website.data.features` and labels (phishing or not phishing) in `y = phiusiil_phishing_url_website.data.targets`.

In [9]:
X = phiusiil_phishing_url_website.data.features
X.tail()

,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,...,Bank,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef
235790,https://www.skincareliving.com,29,www.skincareliving.com,22,0,com,100.000000,1.000000,0.522907,0.058739,...,0,1,0,1,51,7,21,187,2,191
235791,https://www.winchester.gov.uk,28,www.winchester.gov.uk,21,0,uk,100.000000,0.785714,0.028555,0.053834,...,0,1,0,0,50,1,7,88,0,31
235792,https://www.nononsensedesign.be,30,www.nononsensedesign.be,23,0,be,100.000000,1.000000,0.003319,0.063093,...,0,0,0,1,27,10,30,58,2,67
235793,https://patient-cell-40f5.updatedlogmylogin.wo...,55,patient-cell-40f5.updatedlogmylogin.workers.dev,47,0,dev,28.157537,0.465116,0.000961,0.050211,...,0,0,0,0,0,0,3,0,0,0
235794,https://www.alternativefinland.com,33,www.alternativefinland.com,26,0,com,100.000000,1.000000,0.522907,0.060596,...,0,0,0,1,21,6,18,256,0,261

In [10]:
y = phiusiil_phishing_url_website.data.targets
y.tail()

        label
235790      1
235791      1
235792      1
235793      0
235794      1

I'm only interested in URL:s and labels for now, so I will create a new dataframe that includes only these. Later I will make my own features from URL:s

In [12]:
# Combine dataframes
df = pd.concat([phiusiil_phishing_url_website.data.features, phiusiil_phishing_url_website.data.targets], axis=1)
df.head()

,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,0.061933,...,0,0,1,34,20,28,119,0,124,1
1,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,0.050207,...,0,0,1,50,9,8,39,0,217,1
2,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,0.064129,...,0,0,1,10,2,7,42,2,5,1
3,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,0.057606,...,1,1,1,3,27,15,22,1,31,1
4,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,0.059441,...,1,0,1,244,15,34,72,1,85,1

In [ ]:
# Drop all but URL and label and rename label
df = df[["URL", "label"]]

df = df.rename(columns={"label" : "isLegit"})

df.head()

                                  URL  isLegit
0    https://www.southbankmosaics.com        1
1            https://www.uni-mainz.de        1
2      https://www.voicefmradio.co.uk        1
3         https://www.sfnmjournal.com        1
4  https://www.rewildingargentina.org        1

In [ ]:
# Check that there is no null values
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 235795 entries, 0 to 235794
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   URL     235795 non-null  str
 1   label   235795 non-null  int64
dtypes: int64(1), str(1)
memory usage: 3.6 MB